export const startSongList = [
  {
    key: 1,
    title: "As It Was",
    artist: "Harry Styles",
    genre: "Pop",
    youTube: "https://youtu.be/H5v3kku4y6Q",
    score: 3,
  },
  {
    key: 2,
    title: "In the Dark",
    artist: "Purple Disco Machine + Sophie and the Giants",
    genre: "Disco",
    youTube: "https://youtu.be/ZDrlmlzY7cE",
    score: 4,
  },
  {
    key: 3,
    title: "Green Green Grass",
    artist: "George Ezra",
    genre: "Pop",
    youTube: "",
    score: 4,
  },
  {
    key: 4,
    title: "De Diepte",
    artist: "S10",
    genre: "Nederlandstalig",
    youTube: "https://youtu.be/v2m-MGSys0k",
    score: 2,
  },
  {
    key: 5,
    title: "Love Myself",
    artist: "Rondé",
    genre: "Dance",
    youTube: "https://youtu.be/eZqZrWyTjCM",
    score: 4,
  },
  {
    key: 6,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    genre: "Pop",
    youTube: "https://youtu.be/E07s5ZYygMg",
    score: 5,
  },
];
